# Generated by Django 4.2.2 on 2023-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='write something aobut yourself', max_length=30, null=True),
        ),
    ]
