# Generated by Django 4.2.3 on 2023-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dmmessage_seen_alter_dmmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
