# Generated by Django 4.2.3 on 2023-08-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_bio_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='bio',
        ),
    ]
