# Generated by Django 4.2.3 on 2023-08-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_about_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmmessage',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
