# Generated by Django 4.2.3 on 2023-12-02 18:40

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dmmessage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmmessage',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.media_directory_path),
        ),
        migrations.AlterField(
            model_name='dmmessage',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Using whatsclone', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Statu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=api.models.status_directory_path)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
