# Generated by Django 4.2.3 on 2023-12-02 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dmmessage_media_alter_dmmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statu',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
